FROM golang:1.23.4-alpine3.21 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN apk add --no-cache gcc musl-dev sqlite-dev

RUN CGO_ENABLED=1 GOOS=linux go build -o forum main.go

RUN go build -o forum main.go

FROM alpine:latest
WORKDIR /app

RUN apk add --no-cache sqlite-libs

COPY --from=builder /app/forum ./

COPY src ./src
COPY uploads ./uploads
COPY .env .env

EXPOSE 8080

CMD ["./forum"]
